let products=[
["Смартфон Nova X","Электроника",189000,4.8,520],["Ноутбук Air 14","Электроника",399000,4.7,180],["Сымсыз құлаққап","Электроника",24900,4.6,740],["Смарт сағат Fit Pro","Электроника",59000,4.5,410],["4K теледидар","Электроника",329000,4.8,120],
["Ерлер футболкасы","Киім",8900,4.4,680],["Қысқы күртеше","Киім",44900,4.7,310],["Кроссовка Urban","Киім",38900,4.6,450],["Джинсы Classic","Киім",19900,4.3,370],["Худи Basic","Киім",16900,4.5,560],
["Кофе машинасы","Үйге арналған",149000,4.8,160],["Шаңсорғыш","Үйге арналған",89000,4.6,280],["Үстел шамы","Үйге арналған",12900,4.5,490],["Ауа ылғалдатқыш","Үйге арналған",27900,4.4,390],["Ас үй таразысы","Үйге арналған",7900,4.7,610],
["Кофе 1 кг","Азық-түлік",6900,4.9,920],["Шоколад жинағы","Азық-түлік",4500,4.7,840],["Зәйтүн майы","Азық-түлік",5900,4.6,570],["Жаңғақ қоспасы","Азық-түлік",3900,4.8,760],["Бал 500 г","Азық-түлік",4200,4.9,690]
].map((x,i)=>({id:i,name:x[0],category:x[1],price:x[2],rating:x[3],sales:x[4],cluster:0}));
const $=id=>document.getElementById(id), cats=()=>[...new Set(products.map(x=>x.category))];
const names={home:["ЗЕРТХАНА","AI роботты дүкенде оқыту"],teach:["ОҚЫТУ","Роботты оқыту"],classify:["CLASSIFICATION","Тауар классификациясы"],cluster:["CLUSTERING","K-Means кластеризациясы"],data:["DATASET","Оқу деректері"],theory:["THEORY","ML жұмыс принципі"]};
document.querySelectorAll(".nav,.go").forEach(b=>b.onclick=()=>show(b.dataset.page));
function show(p){document.querySelectorAll(".page").forEach(x=>x.classList.remove("active"));$(p).classList.add("active");document.querySelectorAll(".nav").forEach(x=>x.classList.toggle("active",x.dataset.page===p));$("crumb").textContent=names[p][0];$("title").textContent=names[p][1];if(p==="cluster")cluster();if(p==="data")renderTable()}
function norm(data){let ks=["price","rating","sales"],mn={},mx={};ks.forEach(k=>{mn[k]=Math.min(...data.map(x=>x[k]));mx[k]=Math.max(...data.map(x=>x[k]))});return data.map(x=>ks.map(k=>(x[k]-mn[k])/((mx[k]-mn[k])||1)))}
function stats(){let n=products.length;$("mExamples").textContent=n;$("heroCount").textContent=n+" samples";$("memoryCount").textContent=n;$("memorySide").textContent=n+" мысал үйренді";$("mCats").textContent=cats().length;$("memoryFill").style.width=Math.min(100,n/35*100)+"%";$("catMemory").innerHTML=cats().map(c=>`<div><span>${c}</span><b>${products.filter(x=>x.category===c).length}</b></div>`).join("");$("tCat").innerHTML=cats().map(c=>`<option>${c}</option>`).join("")}
function toast(t){$("toast").textContent=t;$("toast").classList.add("show");setTimeout(()=>$("toast").classList.remove("show"),2200)}
$("teachBtn").onclick=()=>{if(!$("tName").value.trim())return toast("Тауар атауын енгізіңіз");products.push({id:Date.now(),name:$("tName").value.trim(),category:$("tCat").value,price:+$("tPrice").value,rating:+$("tRating").value,sales:+$("tSales").value,cluster:0});stats();$("brainStatus").textContent="Жаңа білім қабылданды";$("terminal").innerHTML=`<span>› new sample: ${$("tName").value}</span><span>› label: ${$("tCat").value}</span><span>› model memory updated ✓</span>`;toast("✓ AI жаңа мысалды үйренді");$("tName").value=""}
$("predict").onclick=()=>{let target={price:+$("cPrice").value,rating:+$("cRating").value,sales:+$("cSales").value};let all=[...products,target],N=norm(all),t=N.at(-1);let ds=products.map((p,i)=>({p,d:Math.sqrt(N[i].reduce((s,v,j)=>s+(v-t[j])**2,0))})).sort((a,b)=>a.d-b.d).slice(0,5),votes={};ds.forEach(x=>votes[x.p.category]=(votes[x.p.category]||0)+1);let win=Object.entries(votes).sort((a,b)=>b[1]-a[1])[0],conf=Math.round(win[1]/5*100);$("predCat").textContent=win[0];$("predText").textContent=`AI "${$("cName").value}" тауарын осы категорияға жатқызды.`;$("conf").textContent=conf+"%";$("confFill").style.width=conf+"%";$("neighbors").innerHTML=ds.map((x,i)=>`<div class="neighbor"><span>${i+1}. ${x.p.name}</span><b>${x.p.category}</b></div>`).join("")}
let chart;
function cluster(){let P=norm(products),cent=[P[0].slice(),P[Math.floor(P.length/2)].slice(),P.at(-1).slice()],a=[];for(let z=0;z<40;z++){a=P.map(p=>{let d=cent.map(c=>Math.sqrt(p.reduce((s,v,j)=>s+(v-c[j])**2,0)));return d.indexOf(Math.min(...d))});let nc=cent.map((c,ci)=>{let g=P.filter((_,i)=>a[i]===ci);return g.length?c.map((_,j)=>g.reduce((s,p)=>s+p[j],0)/g.length):c});if(JSON.stringify(nc)===JSON.stringify(cent))break;cent=nc}products.forEach((p,i)=>p.cluster=a[i]);let meta=[0,1,2].map(i=>{let g=products.filter(p=>p.cluster===i);return{i,g,price:g.reduce((s,p)=>s+p.price,0)/(g.length||1),sales:g.reduce((s,p)=>s+p.sales,0)/(g.length||1)}}),hi=[...meta].sort((a,b)=>b.sales-a.sales)[0].i,prem=[...meta].filter(x=>x.i!==hi).sort((a,b)=>b.price-a.price)[0].i,cn={};cn[hi]="Жоғары сұраныс";cn[prem]="Премиум сегмент";meta.forEach(x=>{if(!cn[x.i])cn[x.i]="Орташа сегмент"});let colors=["#5b6cff","#25bfae","#9b61e8"];$("clusterStats").innerHTML=meta.map(x=>`<article><i class="cdot" style="background:${colors[x.i]}"></i><div><small>КЛАСТЕР ${x.i+1}</small><b>${cn[x.i]} • ${x.g.length} тауар</b></div></article>`).join("");$("clusterInfo").innerHTML=meta.map(x=>`<article class="card"><h3>${cn[x.i]}</h3><p>Орташа баға: <b>${Math.round(x.price).toLocaleString()} ₸</b><br>Орташа сатылым: <b>${Math.round(x.sales)}</b><br>AI бұл топты категория атауына қарамай, сандық ұқсастық бойынша құрды.</p></article>`).join("");if(chart)chart.destroy();chart=new Chart($("scatter"),{type:"scatter",data:{datasets:meta.map(x=>({label:cn[x.i],data:x.g.map(p=>({x:p.price,y:p.sales,n:p.name})),backgroundColor:colors[x.i],pointRadius:7,pointHoverRadius:9}))},options:{responsive:true,maintainAspectRatio:false,plugins:{tooltip:{callbacks:{label:c=>`${c.raw.n}: ${c.raw.x.toLocaleString()} ₸ • ${c.raw.y} сатылым`}}},scales:{x:{title:{display:true,text:"Баға, ₸"},grid:{color:"#eef1f5"}},y:{title:{display:true,text:"Сатылым"},grid:{color:"#eef1f5"}}}}});renderTable()}
$("runCluster").onclick=()=>{cluster();toast("✓ K-Means кластерлерді қайта есептеді")}
function renderTable(){clusterSafe();let q=$("search")?.value.toLowerCase()||"";let cn=clusterLabels();$("rows").innerHTML=products.filter(p=>p.name.toLowerCase().includes(q)).map(p=>`<tr><td><b>${p.name}</b></td><td><span class="pill">${p.category}</span></td><td>${p.price.toLocaleString()} ₸</td><td>★ ${p.rating}</td><td>${p.sales}</td><td>${cn[p.cluster]||"Кластер "+(p.cluster+1)}</td></tr>`).join("");$("dataCount").textContent=products.length+" оқу мысалы"}
function clusterSafe(){let P=norm(products),c=[P[0].slice(),P[Math.floor(P.length/2)].slice(),P.at(-1).slice()],a=[];for(let z=0;z<25;z++){a=P.map(p=>{let d=c.map(v=>Math.sqrt(p.reduce((s,x,j)=>s+(x-v[j])**2,0)));return d.indexOf(Math.min(...d))});c=c.map((v,ci)=>{let g=P.filter((_,i)=>a[i]===ci);return g.length?v.map((_,j)=>g.reduce((s,p)=>s+p[j],0)/g.length):v})}products.forEach((p,i)=>p.cluster=a[i])}
function clusterLabels(){let m=[0,1,2].map(i=>{let g=products.filter(p=>p.cluster===i);return{i,pr:g.reduce((s,p)=>s+p.price,0)/(g.length||1),sa:g.reduce((s,p)=>s+p.sales,0)/(g.length||1)}}),hi=[...m].sort((a,b)=>b.sa-a.sa)[0].i,pr=[...m].filter(x=>x.i!==hi).sort((a,b)=>b.pr-a.pr)[0].i,o={};o[hi]="Жоғары сұраныс";o[pr]="Премиум";m.forEach(x=>{if(!o[x.i])o[x.i]="Орташа сегмент"});return o}
$("search").oninput=renderTable;stats();renderTable();